[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run start:all"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "apexel-server"
